sonar.projectKey=wm-operations-sustainability_vasu-portfolio-website
sonar.projectName=vasu-portfolio-website
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/.github/workflows/**,sonar-project.properties
